version: "3"

services:
    app:
        stdin_open: true
        build: .
        image: reactest
        container_name: reactest
        ports:
            - "3000:3000"
        volumes:
            - "./app:/opt/app"
            - "/opt/app/node_modules"
            - "/opt/app/.next"
        environment:
            - CHOKIDAR_USEPOLLING=true
        #commnand: yarn dev